name: Terraform

on: [push]
env:
    AWS_ACCESS-KEY_ID: ${{secrets.ACCESS_KEY}}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/ckeckout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: init
        run: terraform init
      - name: validate
        run: terraform validate
      - name: format
        run: terraform fmt -check
      - name: plan
        run: terraform plan
     
